import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";
import { poppinsFont } from "@/src/utils/fonts";

const inter = Inter({ subsets: ["latin"] });

//TODO: add default SEO metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-screen min-h-screen flex flex-col ${poppinsFont.className} `}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
